### ISSUE TITLE
Source Missing

### ISSUE THREAD

**Issue by Bluotvamp** [struandw/kobold-training-club#114]
Not sure if this counts as an issue, but the Creature Codex doesn't seem to be a source unless I am not seeing it. It was part of Kobold Fight Club, but now that it is gone I have no idea how to get it, and all ID from sources no longer work from the List of community-added KFC. Thanks in advance for any info on this.

**Comment by struandw** [comment]
Thanks for letting me know! I’ve added it to the site - it should show up there now.
