### ISSUE TITLE
Run in Improved Initiative

### ISSUE THREAD

**Issue by vincentscode** [struandw/kobold-training-club#91]
Hi, thanks for creating this amazing replacement for Kobold Fight Club!
One feature I am really missing is the integration of the "Run in Improved Initiative" Button KFC had.
It made it really easy to setup encounters on the fly and use them just seconds later.

The relevant code from KFC can be found here:
https://github.com/Asmor/5e-monsters/blob/master/app/services/integration.service.js

**Comment by struandw** [comment]
Hey, thanks for letting me know about this. I'll definitely look into getting II integration.

**Comment by vincentscode** [comment]
Thanks!
I may look into it myself and create a pull request if I find the time for it and if you are willing to take outside contributions!

**Comment by struandw** [comment]
That’s very kind! I’m more than happy to take contributions - I’m not really a front-end developer at all, so you’d probably be able to do it faster than I can.

**Comment by struandw** [comment]
How would you like to be credited for your work on this?

**Comment by vincentscode** [comment]
Maybe just in a list of contributors on the about page or something like that if you like. 😄
