### ISSUE TITLE
Sorting by CR does not seem to work in Chromium-based browsers

### ISSUE THREAD

**Issue by vincentscode** [struandw/kobold-training-club#92]
All headers sort and change their sorting direction on a click except when clicking on CR (no error is being generated, nothing visually happens).

**Comment by struandw** [comment]
Thanks for letting me know about this!

I can't reproduce this; can you let me know if this is version 0.3.0 (top left hand of the window)? If it is, which browser are you experiencing this on?

**Comment by vincentscode** [comment]
I am using KTC (Version 0.3.0) and Chrome (Version 93.0.4577.82) on Windows 10 (Version 19042.1052).

The Arrows next to "CR" are "illuminating" as expected but the list below does not change.

![cr_sorting](https://user-images.githubusercontent.com/26576880/134697272-810f71f7-f65b-46df-baab-ef15b9c2616b.gif)

**Comment by struandw** [comment]
Ooh, okay, this is really interesting. Is there anything in the developer's console?

The table uses an external library (DataTables) and a custom sort function on the CR column. Now, that custom sort function is almost certainly the problem, but it's working fine on my dev machine (MacOS, Safari), so I'm a little confused here.

**Comment by vincentscode** [comment]
The developer's console is (sometimes) complaining about datatables `load` and `setTimeout` handlers taking too long (on page load) but no additional logs are generated when clicking on "CR".

**Comment by struandw** [comment]
All right, thank you for letting me know. I'll look in to it and see what I can figure out. I assume you've tried clearing your cache & so on?

**Comment by vincentscode** [comment]
I have tried that.
I have also tried other Chromium based browsers (Opera & MS Edge) and encountered the same issue.
It works just fine in Firefox though, so the issue appears to be affecting only Chromium-based browsers.
